POST http://localhost:3001/v1/messages
Content-Type: application/json
Authorization: Bearer  sk-safeai-895850300bc8c085b644c9fda0b5768cd5254b4ba42e2081
anthropic-version: 2023-06-01

{
  "model": "claude-sonnet-4-6",
  "max_tokens": 300,
  "stream": false,
  "messages": [
    {
      "role": "user",
      "content": "Write a simple JavaScript function"
    }
  ]
}


###

POST http://localhost:3001/v1/messages/count_tokens
Content-Type: application/json
Authorization: Bearer  sk-safeai-895850300bc8c085b644c9fda0b5768cd5254b4ba42e2081
anthropic-version: 2023-06-01

{
  "model": "claude-sonnet-4-6",
  "messages": [
    {
      "role": "user",
      "content": "Write a simple JavaScript function"
    }
  ]
}